server:
  port: 8003
spring:
  profiles:
    active: dev
  application:
    # 应用名称也是构成 Nacos 配置管理 dataId 字段的一部分 (当 config.prefix 为空时)
    name: app-test
  cloud:
    nacos:
      # 服务注册发现
      discovery:
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        server-addr: 127.0.0.1:8848
        # server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850 # Nacos 服务器地址
        namespace: 13f6bf83-e288-4d6e-9cc6-1354184b72da
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
      # 配置管理
      config:
        prefix: nacos-client
        file-extension: yaml  # 配置内容的数据格式, 默认为 properties
        enabled: true     # 如果不想使用 Nacos 进行配置管理, 设置为 false 即可
        group: DEFAULT_GROUP  # 组, 默认为 DEFAULT_GROUP
        namespace: 13f6bf83-e288-4d6e-9cc6-1354184b72da
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password:
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always