server:
  port: 8002
spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test-service/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启根据服务名称自动转发
          lower-case-service-id: true #微服务名称已小写形式呈现

    nacos:
      discovery:
        enabled: true # 是否开启Nacos服务注册与发现
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: 13f6bf83-e288-4d6e-9cc6-1354184b72da
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8001/getPublicKey

#  redis:
#    database: 0
#    port: 6379
#    host: 127.0.0.1
#    password:
#    timeout: 1000ms # 连接超时时间
#  sleuth:
#    sampler:
#      # ProbabilityBasedSampler 抽样策略
#      probability: 1.0  # 采样比例, 1.0 表示 100%, 默认是 0.1
#      # RateLimitingSampler 抽样策略, 设置了限速采集, spring.sleuth.sampler.probability 属性值无效
#      rate: 100  # 每秒间隔接受的 trace 量
#  zipkin:
#    sender:
#      type: WEB # 默认是 web
#    base-url: http://127.0.0.1:9411/


# 独立配置，用于GatewayConfig.java中读取监听数据
nacos:
  gateway:
    route:
      config:
        data-id: demo-gateway-router
        group: DEFAULT_GROUP
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

